export enum ActionTasksTypes {
    GET_ALL_TASKS = "GET_ALL_TASKS",
    GET_TASK = "GET_TASK",
    SET_PRIORITY_FILTER = "SET_PRIORITY_FILTER",
    SET_TYPE_FILTER = "SET_TYPE_FILTER",
    SET_IS_DONE_FILTER = "SET_IS_DONE_FILTER",
    DELETE_TASK = "DELETE_TASK",
    POST_TASK = "POST_TASK",
    UPDATE_TASK = "UPDATE_TASK"
}